require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.3
  TargetRailsVersion: 7.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'config/environments/*'
    - 'config/initializers/devise.rb'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'config.ru'
    - 'Rakefile'
    - 'Gemfile'

# Layout Cops
Layout/LineLength:
  Max: 120
  AllowedPatterns:
    - '\A\s*#'  # Allow long comments
  Exclude:
    - 'config/**/*'

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

# Style Cops
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: either

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

# Lint Cops
Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

# Metrics Cops
Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'app/admin/**/*'
    - 'db/seeds.rb'
    - 'test/**/*'

Metrics/ClassLength:
  Max: 250
  Exclude:
    - 'app/admin/**/*'
    - 'test/**/*'

Metrics/ModuleLength:
  Max: 250
  Exclude:
    - 'app/admin/**/*'

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'config/**/*'
    - 'app/admin/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/tasks/**/*'
    - 'Rakefile'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'app/admin/**/*'
    - 'db/seeds.rb'
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'app/admin/**/*'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'app/admin/**/*'

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

# Naming Cops
Naming/VariableNumber:
  EnforcedStyle: snake_case

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_
  AllowedMethods:
    - is_a?

# Rails Cops
Rails:
  Enabled: true

Rails/FilePath:
  EnforcedStyle: arguments

Rails/SkipsModelValidations:
  AllowedMethods:
    - touch
    - update_all
    - update_attribute
    - update_column
    - update_columns

Rails/HasManyOrHasOneDependent:
  Enabled: true

Rails/InverseOf:
  Enabled: true

Rails/ReversibleMigration:
  Enabled: true

Rails/UniqBeforePluck:
  Enabled: true

Rails/BulkChangeTable:
  Enabled: true

Rails/HelperInstanceVariable:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true

Rails/ApplicationMailer:
  Enabled: true

Rails/RakeEnvironment:
  Enabled: true

Rails/ActiveRecordAliases:
  Enabled: true

Rails/Blank:
  Enabled: true

Rails/Present:
  Enabled: true

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_sql

Rails/FindBy:
  Enabled: true

Rails/FindEach:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/**/*'
    - 'db/seeds.rb'

Rails/PluckInWhere:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/WhereNot:
  Enabled: true

# Performance Cops
Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/Sum:
  Enabled: true

Performance/RangeInclude:
  Enabled: true

Performance/RedundantMerge:
  Enabled: true

Performance/StartWith:
  Enabled: true

Performance/EndWith:
  Enabled: true

Performance/RegexpMatch:
  Enabled: true

Performance/UnfreezeString:
  Enabled: true

Performance/DeletePrefix:
  Enabled: true

Performance/DeleteSuffix:
  Enabled: true

Performance/OpenStruct:
  Enabled: true

Performance/InefficientHashSearch:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/RedundantSplitRegexpArgument:
  Enabled: true

Performance/ArraySemiInfiniteRangeSlice:
  Enabled: true

# Minitest Cops (for test suite)
Minitest/MultipleAssertions:
  Max: 10

Minitest/AssertPredicate:
  Enabled: true

Minitest/AssertTruthy:
  Enabled: true

Minitest/RefuteFalse:
  Enabled: true

Minitest/AssertInDelta:
  Enabled: true

Minitest/AssertKindOf:
  Enabled: true

Minitest/AssertOutput:
  Enabled: true

Minitest/AssertPathExists:
  Enabled: true

Minitest/AssertSilent:
  Enabled: true

Minitest/LiteralAsActualArgument:
  Enabled: true

Minitest/UnspecifiedException:
  Enabled: true

Minitest/AssertionInLifecycleHook:
  Enabled: true

Minitest/AssertEmptyLiteral:
  Enabled: true
