x-app: &app
  build:
    context: .
    dockerfile: docker/dev/Dockerfile
  volumes:
    - .:/app
    - qul-bundle:/app/vendor/bundle
    - qul-node-modules:/app/node_modules
  environment:
    DB_HOST: db
    DB_USERNAME: postgres
    DB_PASSWORD: password
    REDIS_URL: redis://redis:6379/0
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_started
  tty: true
  stdin_open: true

services:
  db:
    image: postgres:14
    command: >
      postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=off
    environment:
      POSTGRES_DB: quran_community_tarteel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - qul-postgres-data:/var/lib/postgresql/data
      - ./docker/dev/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - qul-redis-data:/data

  web:
    <<: *app
    command: bin/rails server -b 0.0.0.0 -p 3000
    ports:
      - '3000:3000'

  js:
    <<: *app
    command: npm run build -- --reload
    environment:
      PORT: 3005
    ports:
      - '3005:3005'

  tailwind:
    <<: *app
    command: bin/rails tailwindcss:watch

  sidekiq:
    <<: *app
    command: bundle exec sidekiq

volumes:
  qul-postgres-data:
  qul-redis-data:
  qul-bundle:
  qul-node-modules:
