module Morphology
  module NoorBayan
    module Governors
      MAP = {
        'akad' => 'أكاد',
        'akn' => 'أكن',
        'akon' => 'أكون',
        'an' => 'أنّ',
        'asbah' => 'أصبح',
        'asbaht' => 'أصبحت',
        'barah' => 'برح',
        'dam' => 'دام',
        'dm' => 'دام',
        'easaa' => 'عسى',
        'en' => 'إنّ',
        'in' => 'إنّ',
        'ka' => 'كان',
        "ka'ana" => 'كأنّ',
        'kad' => 'كاد',
        'kan' => 'كان',
        'kant' => 'كانت',
        'kn' => 'كن',
        'kon' => 'كون',
        'la' => 'لا',
        'lakin' => 'لكن',
        'lakun' => 'لكنّ',
        'las' => 'ليس',
        'lays' => 'ليس',
        'layst' => 'ليست',
        'layt' => 'ليت',
        'lel' => 'لعل',
        'ma' => 'ما',
        'nkn' => 'نكن',
        'nko' => 'نك',
        'nkon' => 'نكون',
        "tafta'" => 'تفتأ',
        'tk' => 'تك',
        'tkad' => 'تكاد',
        'tkn' => 'تكن',
        'tknm' => 'تكن',
        'tkon' => 'تكون',
        'tusbih' => 'تصبح',
        'yazal' => 'يزال',
        'yk' => 'يك',
        'ykad' => 'يكاد',
        'ykn' => 'يكن',
        'ykon' => 'يكون',
        'ysbah' => 'يصبح',
        'zala' => 'ظل'
      }.freeze
    end
  end
end
