daily_backup:
  class: BackupJob
  cron: "0 10 * * *"
  description: "Daily database backup job"

quran_enc_update_checker:
  class: DraftContent::CheckContentChangesJob
  cron: "0 6 * * 0"
  description: "Weekly job to check for translation and tafsir changes from sources"