const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  content: [
    "./public/*.html",
    "./app/helpers/**/*.rb",
    "./app/javascript/**/*.{js,vue}",
    "./app/views/**/*.{erb,html}",
    "./app/components/**/*.{erb,html}",
    "./app/admin/**/*.rb",
  ],
  theme: {
    extend: {
      fontFamily: {
        sarina: ["Sarina", "cursive"],
        inter: ["Inter", "sans-serif"],
        title: ["Open Sauce Sans", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
    require("@tailwindcss/container-queries"),
  ],
  safelist: [
    "bg-red-100",
    "bg-blue-100",
    "bg-orange-100",
    "bg-green-100",
    "bg-yellow-100",

    "text-red-600",
    "text-blue-600",
    "text-orange-600",
    "text-green-600",
    "text-yellow-600",
    "text-green-500",
    "hidden",
    "link-button",
    "qul-docs",
    "qul-docs *",
    "tw-docs",
    "tw-docs *",
    "tw-docs-code-block",
    "tw-docs-code-header",
    "tw-docs-code-language",
    "tw-docs-code-actions",
    "tw-docs-code-button",
    "tw-docs-playground",
    "tw-docs-playground-grid",
    "tw-docs-playground-pane",
    "tw-docs-playground-label",
    "tw-docs-playground-editor",
    "tw-docs-playground-preview",

    "btn",
    "btn-primary",
    "btn-secondary",
    "btn-outline",
    "btn-dark",
    "btn-tab",
    "btn-tab-active",
    "btn-toggle",
    "btn-toggle-active",
    "btn-info",
    "btn-success",
    "btn-danger",
    "btn-outline-info",
    "btn-outline-success",
    "btn-sm",
    "btn-lg",
    "btn-cta",
    "btn-outline-dark",
    "btn-outline-pill",

    "nav-link--active",

    "flex",
    "flex-col",
    "items-end",
    "ms-auto",
    "me-2",
    "m-1",
    "my-2",
    "p-3",
    "py-2",

    "badge",
    "badge-default",
    "badge-success",
    "badge-danger",
    "badge-warning",
    "badge-info",
    "badge-purple",
    "badge-resource",
    "badge-pill",
    "badge-outline-default",
    "badge-outline-success",
    "badge-outline-danger",
    "badge-outline-warning",
    "badge-outline-info",
    "badge-outline-purple",

    "tag",
    "tag-orange",
    "tag-blue",
    "tag-green",
    "tag-red",
  ],
};
