const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  prefix: "tw-",
  content: [
    "./public/*.html",
    "./app/helpers/**/*.rb",
    "./app/javascript/**/*.{js,vue}",
    "./app/views/**/*.{erb,html}",
    "./app/admin/**/*.rb",
  ],
  theme: {
    extend: {
      fontFamily: {
        sarina: ["Sarina", "cursive"],
        inter: ["Inter", "sans-serif"],
        title: ["Open Sauce Sans", "sans-serif"],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
    require("@tailwindcss/container-queries"),
  ],
  safelist: [
    "tw-bg-red-100",
    "tw-bg-blue-100",
    "tw-bg-orange-100",
    "tw-bg-green-100",
    "tw-bg-yellow-100",

    "tw-text-red-600",
    "tw-text-blue-600",
    "tw-text-orange-600",
    "tw-text-green-600",
    "tw-text-yellow-600",
    "tw-text-green-500",
    "tw-docs",
    "tw-docs *",

    // Button classes
    "btn",
    "btn-primary",
    "btn-secondary",
    "btn-outline",
    "btn-dark",
    "btn-tab",
    "btn-tab-active",
    "btn-toggle",
    "btn-toggle-active",
    "btn-info",
    "btn-success",
    "btn-danger",
    "btn-outline-info",
    "btn-outline-success",
    "btn-sm",
    "btn-lg",
    "btn-cta",
    "btn-outline-dark",
    "btn-outline-pill",

    "tw-flex",
    "tw-flex-col",
    "tw-items-end",
    "tw-ms-auto",
    "tw-me-2",
    "tw-m-1",
    "tw-my-2",
    "tw-p-3",
    "tw-py-2",

    // Badge classes
    "badge",
    "badge-default",
    "badge-success",
    "badge-danger",
    "badge-warning",
    "badge-info",
    "badge-purple",
    "badge-resource",
    "badge-pill",
    "badge-outline-default",
    "badge-outline-success",
    "badge-outline-danger",
    "badge-outline-warning",
    "badge-outline-info",
    "badge-outline-purple",
  ],
};
