module Utils
  module Arabic
    module Letters
      class QpcHafs < Letters::Letter
        # https://github.com/GlobalQuran/gq-tool/blob/master/lib/tajweed/util/normlise.rb
        SPACE = Letter.new(name: 'SPACE', char: ' ', unicode: "\u0020")
        NO_BREAK_SPACE = Letter.new(name: 'NO-BREAK_SPACE', char: ' ', unicode: "\u00a0")
        LETTER_HAMZA = Letter.new(name: 'LETTER_HAMZA', char: 'ء', unicode: "\u0621")
        LETTER_ALEF_WITH_HAMZA_ABOVE = Letter.new(name: 'LETTER_ALEF_WITH_HAMZA_ABOVE', char: 'أ', unicode: "\u0623")
        LETTER_WAW_WITH_HAMZA_ABOVE = Letter.new(name: 'LETTER_WAW_WITH_HAMZA_ABOVE', char: 'ؤ', unicode: "\u0624")
        LETTER_ALEF_WITH_HAMZA_BELOW = Letter.new(name: 'LETTER_ALEF_WITH_HAMZA_BELOW', char: 'إ', unicode: "\u0625")
        LETTER_YEH_WITH_HAMZA_ABOVE = Letter.new(name: 'LETTER_YEH_WITH_HAMZA_ABOVE', char: 'ئ', unicode: "\u0626")
        LETTER_ALEF = Letter.new(name: 'LETTER_ALEF', char: 'ا', unicode: "\u0627")
        LETTER_BEH = Letter.new(name: 'LETTER_BEH', char: 'ب', unicode: "\u0628")
        LETTER_TEH_MARBUTA = Letter.new(name: 'LETTER_TEH_MARBUTA', char: 'ة', unicode: "\u0629")
        LETTER_TEH = Letter.new(name: 'LETTER_TEH', char: 'ت', unicode: "\u062a")
        LETTER_THEH = Letter.new(name: 'LETTER_THEH', char: 'ث', unicode: "\u062b")
        LETTER_JEEM = Letter.new(name: 'LETTER_JEEM', char: 'ج', unicode: "\u062c")
        LETTER_HAH = Letter.new(name: 'LETTER_HAH', char: 'ح', unicode: "\u062d")
        LETTER_KHAH = Letter.new(name: 'LETTER_KHAH', char: 'خ', unicode: "\u062e")
        LETTER_DAL = Letter.new(name: 'LETTER_DAL', char: 'د', unicode: "\u062f")
        LETTER_THAL = Letter.new(name: 'LETTER_THAL', char: 'ذ', unicode: "\u0630")
        LETTER_REH = Letter.new(name: 'LETTER_REH', char: 'ر', unicode: "\u0631")
        LETTER_ZAIN = Letter.new(name: 'LETTER_ZAIN', char: 'ز', unicode: "\u0632")
        LETTER_SEEN = Letter.new(name: 'LETTER_SEEN', char: 'س', unicode: "\u0633")
        LETTER_SHEEN = Letter.new(name: 'LETTER_SHEEN', char: 'ش', unicode: "\u0634")
        LETTER_SAD = Letter.new(name: 'LETTER_SAD', char: 'ص', unicode: "\u0635")
        LETTER_DAD = Letter.new(name: 'LETTER_DAD', char: 'ض', unicode: "\u0636")
        LETTER_TAH = Letter.new(name: 'LETTER_TAH', char: 'ط', unicode: "\u0637")
        LETTER_ZAH = Letter.new(name: 'LETTER_ZAH', char: 'ظ', unicode: "\u0638")
        LETTER_AIN = Letter.new(name: 'LETTER_AIN', char: 'ع', unicode: "\u0639")
        LETTER_GHAIN = Letter.new(name: 'LETTER_GHAIN', char: 'غ', unicode: "\u063a")
        TATWEEL = Letter.new(name: 'TATWEEL', char: 'ـ', unicode: "\u0640")
        LETTER_FEH = Letter.new(name: 'LETTER_FEH', char: 'ف', unicode: "\u0641")
        LETTER_QAF = Letter.new(name: 'LETTER_QAF', char: 'ق', unicode: "\u0642")
        LETTER_KAF = Letter.new(name: 'LETTER_KAF', char: 'ك', unicode: "\u0643")
        LETTER_LAM = Letter.new(name: 'LETTER_LAM', char: 'ل', unicode: "\u0644")
        LETTER_MEEM = Letter.new(name: 'LETTER_MEEM', char: 'م', unicode: "\u0645")
        LETTER_NOON = Letter.new(name: 'LETTER_NOON', char: 'ن', unicode: "\u0646")
        LETTER_HEH = Letter.new(name: 'LETTER_HEH', char: 'ه', unicode: "\u0647")
        LETTER_WAW = Letter.new(name: 'LETTER_WAW', char: 'و', unicode: "\u0648")
        LETTER_ALEF_MAKSURA = Letter.new(name: 'LETTER_ALEF_MAKSURA', char: 'ى', unicode: "\u0649")
        LETTER_YEH = Letter.new(name: 'LETTER_YEH', char: 'ي', unicode: "\u064a")
        FATHATAN = Letter.new(name: 'FATHATAN', char: 'ً', unicode: "\u064b")
        DAMMATAN = Letter.new(name: 'DAMMATAN', char: 'ٌ', unicode: "\u064c")
        KASRATAN = Letter.new(name: 'KASRATAN', char: 'ٍ', unicode: "\u064d")
        FATHA = Letter.new(name: 'FATHA', char: 'َ', unicode: "\u064e")
        DAMMA = Letter.new(name: 'DAMMA', char: 'ُ', unicode: "\u064f")
        KASRA = Letter.new(name: 'KASRA', char: 'ِ', unicode: "\u0650")
        SHADDA = Letter.new(name: 'SHADDA', char: 'ّ', unicode: "\u0651")
        SUKUN = Letter.new(name: 'SUKUN', char: 'ْ', unicode: "\u0652")
        MADDAH_ABOVE = Letter.new(name: 'MADDAH_ABOVE', char: 'ٓ', unicode: "\u0653")
        HAMZA_ABOVE = Letter.new(name: 'HAMZA_ABOVE', char: 'ٔ', unicode: "\u0654")
        HAMZA_BELOW = Letter.new(name: 'HAMZA_BELOW', char: 'ٕ', unicode: "\u0655")
        SUBSCRIPT_ALEF = Letter.new(name: 'SUBSCRIPT_ALEF', char: 'ٖ', unicode: "\u0656")
        INVERTED_DAMMA = Letter.new(name: 'INVERTED_DAMMA', char: 'ٗ', unicode: "\u0657")
        FATHA_WITH_TWO_DOTS = Letter.new(name: 'FATHA_WITH_TWO_DOTS', char: 'ٞ', unicode: "\u065e")
        LETTER_SUPERSCRIPT_ALEF = Letter.new(name: 'LETTER_SUPERSCRIPT_ALEF', char: 'ٰ', unicode: "\u0670")
        LETTER_ALEF_WASLA = Letter.new(name: 'LETTER_ALEF_WASLA', char: 'ٱ', unicode: "\u0671")
        SMALL_HIGH_LIGATURE_SAD_WITH_LAM_WITH_ALEF_MAKSURA = Letter.new(name: 'SMALL_HIGH_LIGATURE_SAD_WITH_LAM_WITH_ALEF_MAKSURA', char: 'ۖ', unicode: "\u06d6")
        SMALL_HIGH_LIGATURE_QAF_WITH_LAM_WITH_ALEF_MAKSURA = Letter.new(name: 'SMALL_HIGH_LIGATURE_QAF_WITH_LAM_WITH_ALEF_MAKSURA', char: 'ۗ', unicode: "\u06d7")
        SMALL_HIGH_MEEM_INITIAL_FORM = Letter.new(name: 'SMALL_HIGH_MEEM_INITIAL_FORM', char: 'ۘ', unicode: "\u06d8")
        SMALL_HIGH_JEEM = Letter.new(name: 'SMALL_HIGH_JEEM', char: 'ۚ', unicode: "\u06da")
        SMALL_HIGH_THREE_DOTS = Letter.new(name: 'SMALL_HIGH_THREE_DOTS', char: 'ۛ', unicode: "\u06db")
        SMALL_HIGH_SEEN = Letter.new(name: 'SMALL_HIGH_SEEN', char: 'ۜ', unicode: "\u06dc")
        START_OF_RUB_EL_HIZB = Letter.new(name: 'START_OF_RUB_EL_HIZB', char: '۞', unicode: "\u06de")
        SMALL_HIGH_UPRIGHT_RECTANGULAR_ZERO = Letter.new(name: 'SMALL_HIGH_UPRIGHT_RECTANGULAR_ZERO', char: '۠', unicode: "\u06e0")
        SMALL_HIGH_DOTLESS_HEAD_OF_KHAH = Letter.new(name: 'SMALL_HIGH_DOTLESS_HEAD_OF_KHAH', char: 'ۡ', unicode: "\u06e1")
        SMALL_HIGH_MEEM_ISOLATED_FORM = Letter.new(name: 'SMALL_HIGH_MEEM_ISOLATED_FORM', char: 'ۢ', unicode: "\u06e2")
        SMALL_HIGH_MADDA = Letter.new(name: 'SMALL_HIGH_MADDA', char: 'ۤ', unicode: "\u06e4")
        SMALL_WAW = Letter.new(name: 'SMALL_WAW', char: 'ۥ', unicode: "\u06e5")
        SMALL_YEH = Letter.new(name: 'SMALL_YEH', char: 'ۦ', unicode: "\u06e6")
        SMALL_HIGH_YEH = Letter.new(name: 'SMALL_HIGH_YEH', char: 'ۧ', unicode: "\u06e7")
        SMALL_HIGH_NOON = Letter.new(name: 'SMALL_HIGH_NOON', char: 'ۨ', unicode: "\u06e8")
        PLACE_OF_SAJDAH = Letter.new(name: 'PLACE_OF_SAJDAH', char: '۩', unicode: "\u06e9")
        EMPTY_CENTRE_LOW_STOP = Letter.new(name: 'EMPTY_CENTRE_LOW_STOP', char: '۪', unicode: "\u06ea")
        ROUNDED_HIGH_STOP_WITH_FILLED_CENTRE = Letter.new(name: 'ROUNDED_HIGH_STOP_WITH_FILLED_CENTRE', char: '۬', unicode: "\u06ec")
        SMALL_LOW_MEEM = Letter.new(name: 'SMALL_LOW_MEEM', char: 'ۭ', unicode: "\u06ed")
        INDIC_DIGIT_ZERO = Letter.new(name: 'INDIC_DIGIT_ZERO', char: '٠', unicode: "\u0660")
        INDIC_DIGIT_ONE = Letter.new(name: 'INDIC_DIGIT_ONE', char: '١', unicode: "\u0661")
        INDIC_DIGIT_TWO = Letter.new(name: 'INDIC_DIGIT_TWO', char: '٢', unicode: "\u0662")
        INDIC_DIGIT_THREE = Letter.new(name: 'INDIC_DIGIT_THREE', char: '٣', unicode: "\u0663")
        INDIC_DIGIT_FOUR = Letter.new(name: 'INDIC_DIGIT_FOUR', char: '٤', unicode: "\u0664")
        INDIC_DIGIT_FIVE = Letter.new(name: 'INDIC_DIGIT_FIVE', char: '٥', unicode: "\u0665")
        INDIC_DIGIT_SIX = Letter.new(name: 'INDIC_DIGIT_SIX', char: '٦', unicode: "\u0666")
        INDIC_DIGIT_SEVEN = Letter.new(name: 'INDIC_DIGIT_SEVEN', char: '٧', unicode: "\u0667")
        INDIC_DIGIT_EIGHT = Letter.new(name: 'INDIC_DIGIT_EIGHT', char: '٨', unicode: "\u0668")
        INDIC_DIGIT_NINE = Letter.new(name: 'INDIC_DIGIT_NINE', char: '٩', unicode: "\u0669")
      end
    end
  end
end




