1:
  - Fatihah
  - Fatiha
  - Fateha
  - Fateh
  - Al Fatiha
  - Al Fatihah
  - فاتحہ
2:
  - Baqarah
  - Baqara
  - Baqarahh
  - Baqrah
  - Bakarah
  - Al Baqarah
3:
  - Ali Imran
  - Aal Imran
  - Ale Imran
  - Aali Imran
  - Al Imran
  - آل عمران
4:
  - Nisa
  - Nisaa
  - Al Nisa
  - An Nisa
  - النساء
5:
  - Maidah
  - Maida
  - Maaidah
  - Al Maidah
  - Al Maida
6:
  - Anam
  - Anaam
  - Al Anam
  - Al Anaam
7:
  - Araf
  - Araaf
  - Al Araf
  - Al Araaf
8:
  - Anfal
  - Anfaal
  - Al Anfal
9:
  - Tawbah
  - Taubah
  - Tauba
  - Toba
  - Towbah
  - Surah Taubah
  - Baraah
  - Baraa
  - Baraat
10:
  - Yunus
  - Younus
  - Yunas
  - Yونس
  - Jonas
11:
  - Hud
  - Hood
  - Huud
  - Hūd
12:
  - Yusuf
  - Yousuf
  - Yousaf
  - Yusaf
  - Joseph
13:
  - Raad
  - Ra’d
  - Rad
  - Al Raad
  - Ar Raad
14:
  - Ibrahim
  - Ibraheem
  - Ibrahym
  - Abraham
15:
  - Hijr
  - Hajr
  - Al Hijr
16:
  - Nahl
  - Nehl
  - Al Nahl
17:
  - Isra
  - Israa
  - Al Isra
  - Bani Israil
  - Bani Israel
  - بنی اسرائیل
  - Children of Israel
18:
  - Kahf
  - Kehf
  - Kahaf
  - Al Kahf
  - The Cave
19:
  - Maryam
  - Mariam
  - Maryum
  - Mary
20:
  - Taha
  - Ta Ha
  - Ta-Ha
  - Taaha
  - طہ
21:
  - Anbiya
  - Ambiya
  - Anbiyaa
  - Al Anbiya
  - Prophets
22:
  - Hajj
  - Haj
  - Al Hajj
23:
  - Muminun
  - Mu’minun
  - Muminoon
  - Mominoon
  - Al Muminun
  - Believers
24:
  - Nur
  - Noor
  - Al Nur
  - Al Noor
  - The Light
25:
  - Furqan
  - Furqaan
  - Al Furqan
  - Criterion
26:
  - Shuara
  - Shuaraa
  - Shu’ara
  - Shoara
  - Al Shuara
  - Ash Shuara
  - Poets
27:
  - Naml
  - Al Naml
  - The Ant
  - Ants
28:
  - Qasas
  - Kasas
  - Qassas
  - Al Qasas
  - Stories
29:
  - Ankabut
  - Ankaboot
  - Al Ankabut
  - Spider
30:
  - Rum
  - Room
  - Al Rum
  - Ar Rum
  - Romans
31:
  - Luqman
  - Luqmaan
  - Lokman
  - لقمان
32:
  - Sajda
  - Sajdah
  - Sajdaah
  - Al Sajdah
  - Prostration
33:
  - Ahzab
  - Ahzaab
  - Al Ahzab
  - Confederates
34:
  - Saba
  - Sabaa
  - Sheba
35:
  - Fatir
  - Faatir
  - Al Fatir
  - Creator
36:
  - Yaseen
  - Yasin
  - Ya Seen
  - Ya Sin
  - Ya-Sin
  - Yasin Sharif
37:
  - Saffat
  - Saffaat
  - Al Saffat
  - As Saffat
38:
  - Sad
  - Saad
  - Surah Saad
  - Suad
  - ص
39:
  - Zumar
  - Al Zumar
  - Az Zumar
  - Groups
40:
  - Ghafir
  - Al Ghafir
  - Mumin
  - Al Mumin
  - Surah Mumin
  - The Forgiver
  - The Believer
41:
  - Fussilat
  - Fusilat
  - Ha Mim Sajdah
  - Hameem Sajdah
  - حم السجدة
42:
  - Shura
  - Shuraa
  - Shoora
  - Al Shura
  - Ash Shura
  - Consultation
43:
  - Zukhruf
  - Al Zukhruf
  - Az Zukhruf
  - Ornaments of Gold
44:
  - Dukhan
  - Dukhaan
  - Duhan
  - Al Dukhan
  - Smoke
45:
  - Jathiya
  - Jathiyah
  - Jaathiyah
  - Al Jathiyah
  - Kneeling
46:
  - Ahqaf
  - Ahqaaf
  - Al Ahqaf
47:
  - Muhammad
  - Mohammad
  - Muhammed
  - Surah Muhammad
  - Prophet Muhammad
48:
  - Fath
  - Fateh
  - Al Fath
  - Victory
49:
  - Hujurat
  - Hujuraat
  - Al Hujurat
  - Rooms
  - Chambers
50:
  - Qaf
  - Qaaf
  - Kaf
  - ق
51:
  - Dhariyat
  - Dhariyaat
  - Zariyat
  - Zariyaat
  - Az Zariyat
  - Adh Dhariyat
  - The Winnowing Winds
52:
  - Tur
  - Toor
  - Al Toor
  - At Tur
  - Mount Tur
  - Mount Sinai
53:
  - Najm
  - Najam
  - Al Najm
  - An Najm
  - The Star
54:
  - Qamar
  - Kamar
  - Al Qamar
  - Moon
55:
  - Rahman
  - Rehman
  - Ar Rahman
  - الرحمن
  - Most Merciful
56:
  - Waqiah
  - Waqia
  - Waqi’a
  - Waqi’ah
  - Al Waqiah
  - The Inevitable
57:
  - Hadid
  - Hadeed
  - Al Hadid
  - Iron
58:
  - Mujadila
  - Mujadalah
  - Mijadila
  - Al Mujadila
  - The Pleading Woman
59:
  - Hashr
  - Al Hashr
  - Exile
  - Gathering
60:
  - Mumtahanah
  - Mumtahana
  - Mumtahina
  - Al Mumtahanah
  - The Woman to be Examined
61:
  - Saff
  - Al Saff
  - As Saff
  - The Ranks
62:
  - Jumuah
  - Jumu’ah
  - Jumu’ah
  - Juma
  - Jummah
  - Al Juma
  - Al Jumuah
  - Friday
63:
  - Munafiqun
  - Munafiqoon
  - Munafiqin
  - Al Munafiqun
  - Hypocrites
64:
  - Taghabun
  - Tagabun
  - Taghaabun
  - Al Taghabun
  - At Taghabun
  - Mutual Loss and Gain
65:
  - Talaq
  - Talaak
  - Al Talaq
  - At Talaq
  - Divorce
66:
  - Tahrim
  - Tahreem
  - Al Tahrim
  - At Tahrim
  - Prohibition
67:
  - Mulk
  - Al Mulk
  - Mulk Sharif
  - الملك
  - Kingdom
  - Dominion
68:
  - Qalam
  - Kalam
  - Al Qalam
  - Pen
69:
  - Haqqah
  - Haqqa
  - Al Haqqah
  - The Reality
70:
  - Maarij
  - Ma’arij
  - Ma’arij
  - Mairaj
  - Al Maarij
  - Ascending Stairways
71:
  - Nuh
  - Nooh
  - Noah
72:
  - Jinn
  - Jin
  - Al Jinn
  - The Jinn
73:
  - Muzzammil
  - Muzammil
  - Al Muzzammil
  - The Enshrouded One
74:
  - Muddaththir
  - Muddathir
  - Muddassir
  - Mudathir
  - Al Muddaththir
  - The Cloaked One
75:
  - Qiyamah
  - Qiyama
  - Qiyamat
  - Al Qiyamah
  - قیامت
  - Resurrection
76:
  - Insan
  - Insaan
  - Al Insan
  - Inسان
  - Dahr
  - Ad-Dahr
  - Ad Dahr
  - Dahar
  - Time
  - Man
77:
  - Mursalat
  - Mursalaat
  - Al Mursalat
  - Those Sent Forth
78:
  - Naba
  - Nabaa
  - An Naba
  - Amma
  - Amma Yatasaaloon
  - The Great News
79:
  - Naziat
  - Naaziat
  - Nazi’aat
  - Al Naziat
  - Those Who Pull Out
80:
  - Abasa
  - Abasaa
  - Abasa wa tawalla
  - He Frowned
81:
  - Takwir
  - Takweer
  - Al Takwir
  - At Takwir
  - Folding Up
82:
  - Infitar
  - Al Infitar
  - Cleaving
83:
  - Mutaffifin
  - Mutafifin
  - Mutaffifeen
  - Al Mutaffifin
  - Defrauding
84:
  - Inshiqaq
  - Inshikak
  - Al Inshiqaq
  - Splitting Open
85:
  - Buruj
  - Burooj
  - Al Buruj
  - Constellations
86:
  - Tariq
  - Taariq
  - Tarik
  - Al Tariq
  - At Tariq
  - Nightcomer
87:
  - Ala
  - Aala
  - A’la
  - A’la
  - Al Ala
  - Al Aala
  - Al A’la
  - Most High
88:
  - Ghashiyah
  - Gashiyah
  - Al Ghashiyah
  - Overwhelming Event
89:
  - Fajr
  - Al Fajr
  - Dawn
90:
  - Balad
  - Al Balad
  - The City
91:
  - Shams
  - Al Shams
  - Ash Shams
  - The Sun
92:
  - Layl
  - Lail
  - Al Layl
  - Al Lail
  - The Night
93:
  - Duha
  - Duhaa
  - Dhuha
  - Zuha
  - Al Duha
  - Ad Duha
  - الضحى
  - Morning Brightness
94:
  - Sharh
  - Inshirah
  - Alam Nashrah
  - Alam Nashra
  - Ash Sharh
  - Al Inshirah
  - The Relief
  - The Opening Up
95:
  - Tin
  - Teen
  - Al Tin
  - At Tin
  - The Fig
96:
  - Alaq
  - Al ’Alaq
  - Iqra
  - Iqraa
  - Surah Iqra
  - Clot
  - Read
97:
  - Qadr
  - Qadar
  - Al Qadr
  - Laylatul Qadr
  - Night of Decree
  - Power
98:
  - Bayyinah
  - Bayyina
  - Al Bayyinah
  - Al Bayyina
  - Clear Proof
99:
  - Zalzalah
  - Zalzala
  - Zilzal
  - Al Zalzalah
  - Az Zalzalah
  - Earthquake
100:
  - Adiyat
  - Aadiyat
  - Adiyaat
  - Al Adiyat
  - The Courser
  - Charging Horses
101:
  - Qariah
  - Qaari’ah
  - Qariya
  - Kariyah
  - Al Qariah
  - The Calamity
102:
  - Takathur
  - Takaathur
  - Al Takathur
  - At Takathur
  - Rivalry in World Increase
103:
  - Asr
  - Al Asr
  - العصر
  - Time
104:
  - Humazah
  - Humaza
  - Al Humazah
  - Slanderer
105:
  - Fil
  - Feel
  - Al Fil
  - Elephant
  - The Elephant
106:
  - Quraysh
  - Quraish
  - Quresh
  - Kuraish
107:
  - Maun
  - Maaun
  - Ma’oon
  - Ma’oon
  - Al Maun
  - Small Kindnesses
108:
  - Kawthar
  - Kauthar
  - Kawsar
  - Kausar
  - Al Kawthar
  - Al Kausar
  - Abundance
109:
  - Kafirun
  - Kafiroon
  - Al Kafirun
  - Al Kafiroon
  - Disbelievers
110:
  - Nasr
  - Nusr
  - Al Nasr
  - An Nasr
  - Help
  - Victory
111:
  - Masad
  - Lahab
  - Abu Lahab
  - Tabbat
  - Tabbat Yada
  - Tabbat Yada Abi Lahab
  - Palm Fiber
112:
  - Ikhlas
  - Ikhlaas
  - Al Ikhlas
  - Qul Huwallahu Ahad
  - قل هو الله احد
  - Sincerity
  - Purity of Faith
113:
  - Falaq
  - Falak
  - Al Falaq
  - Qul Auzu bi Rabbil Falaq
  - Dawnbreak
114:
  - Nas
  - Naas
  - Al Nas
  - An Nas
  - Qul Auzu bi Rabbin Nas
  - Mankind
